In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
import warnings
from scipy import sparse

In [3]:
x_train=[[1,2,0],[0,6,0],[0,4,0]]

SCALEING

In [4]:
train_sp_csr = sparse.csr_matrix(x_train)
print(train_sp_csr)

  (0, 0)	1
  (0, 1)	2
  (1, 1)	6
  (2, 1)	4


In [5]:
train_sp_csc = sparse.csc_matrix(x_train)
print(train_sp_csc)

  (0, 0)	1
  (0, 1)	2
  (1, 1)	6
  (2, 1)	4


MaxAbsScaler

In [6]:
scaler = preprocessing.MaxAbsScaler().fit(x_train)
scaled = scaler.transform(x_train)
print(scaled)

[[1.         0.33333333 0.        ]
 [0.         1.         0.        ]
 [0.         0.66666667 0.        ]]


In [7]:
scaler = preprocessing.MaxAbsScaler().fit(train_sp_csr)     # Compressed
scaled = scaler.transform(train_sp_csr)
print(scaled)

  (0, 0)	1.0
  (0, 1)	0.3333333333333333
  (1, 1)	1.0
  (2, 1)	0.6666666666666666


StandardScaler

In [8]:
scaler = preprocessing.StandardScaler(with_mean=False).fit(x_train)
std_scaled = scaler.transform(x_train)
print(std_scaled)

[[2.12132034 1.22474487 0.        ]
 [0.         3.67423461 0.        ]
 [0.         2.44948974 0.        ]]


In [9]:
scaler = preprocessing.StandardScaler(with_mean=False).fit(x_train)   # Compressed
std_scaled = scaler.transform(x_train)
print(std_scaled)

[[2.12132034 1.22474487 0.        ]
 [0.         3.67423461 0.        ]
 [0.         2.44948974 0.        ]]


ROBUST SCALER

In [10]:
x_train=np.array([(1,2,3),(4,5,6),(7,9999,9999)])   # data with outliers
x_train

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7, 9999, 9999]])

In [11]:
scaler = preprocessing.RobustScaler().fit(x_train)   # Robust Scaling
rd_scaled = scaler.transform(x_train)
print(rd_scaled)

[[-1.00000000e+00 -6.00180054e-04 -6.00240096e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.99939982e+00  1.99939976e+00]]


In [12]:
scaler = preprocessing.StandardScaler().fit(x_train)   # Robust Scaling
sd_scaled = scaler.transform(x_train)
print(rd_scaled.round(1))

[[-1. -0. -0.]
 [ 0.  0.  0.]
 [ 1.  2.  2.]]


In [13]:
scaler = preprocessing.MaxAbsScaler().fit(x_train)   # MaxAbs Scaling
rd_scaled = scaler.transform(x_train)
print(rd_scaled)

[[1.42857143e-01 2.00020002e-04 3.00030003e-04]
 [5.71428571e-01 5.00050005e-04 6.00060006e-04]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]


KernalCenter

In [17]:
x=np.array([[1,2,3],[3,2,1],[2,1,3]])
x

array([[1, 2, 3],
       [3, 2, 1],
       [2, 1, 3]])

In [19]:
scaler = preprocessing.KernelCenterer().fit(x)


In [20]:
print(scaler.K_fit_rows_)

[2.         1.66666667 2.33333333]


In [21]:
print(scaler.K_fit_all_)

2.0


In [23]:
x_center = scaler.transform(x)
x_center

array([[-1.        ,  0.33333333,  0.66666667],
       [ 1.        ,  0.33333333, -1.33333333],
       [ 0.        , -0.66666667,  0.66666667]])

In [27]:
np.mean(x_center,axis=1).round(2)    # Column

array([-0., -0., -0.])

In [28]:
np.mean(x_center,axis=0).round(2)    # rows

array([ 0., -0., -0.])